language: go
go:
  - "1.9"
  - "1.10"
  - "1.11"
  - master
install:
  - go get -v -t ./...
script:
  - make help
  - make install
  - make cover || echo 'Failed'
  - go test -v -cover -coverprofile=coverage.out -covermode=count ./{,cmd,internal,providers}/... || echo 'Failed'
  - go test -v -cover -coverprofile=coverage.out -covermode=count ./... || echo 'Failed'
  - go test --tags test -v -cover -coverprofile=coverage.out -covermode=count ./{,cmd,internal,providers}/... || echo 'Failed'
  - go test --tags test -v -cover -coverprofile=coverage.out -covermode=count ./... || echo 'Failed'
  - go test --tags test -v -cover -coverprofile=coverage.out -covermode=count github.com/itsfunky/funky/{,cmd,internal,providers}/... || echo 'Failed'
  - go test --tags test -v -cover -coverprofile=coverage.out -covermode=count github.com/itsfunky/funky/... || echo 'Failed'
jobs:
  fast_finish: true
  allow_failures:
    - go: master
notifications:
  email:
    on_success: change
    on_failure: always
