language: go
go:
  - "1.9"
  - "1.10"
  - "1.11"
  - master
script:
  - make help
  - make install
  - make cover
jobs:
  fast_finish: true
  allow_failures:
    - go: master
notifications:
  email:
    on_success: change
    on_failure: always
